/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./layouts/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
    "./utils/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // Every colour resolves to a token in styles/tokens.css, so switching
      // [data-theme] retints utilities and raw CSS together and neither can
      // drift from the other.
      colors: {
        bg: "var(--bg)",
        surface: "var(--surface)",
        ink: "var(--ink)",
        muted: "var(--muted)",
        faint: "var(--faint)",
        accent: "var(--accent)",
        line: "var(--line)",
      },
      borderColor: { DEFAULT: "var(--line)" },
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ["var(--font-serif)", "Georgia", "serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
        lg: "var(--radius-lg)",
      },
      transitionTimingFunction: { out: "var(--ease-out)" },
      transitionDuration: {
        fast: "var(--motion-fast)",
        base: "var(--motion-base)",
        slow: "var(--motion-slow)",
      },
      typography: {
        DEFAULT: {
          css: {
            fontSize: "15px",
            lineHeight: "1.7",
            color: "var(--ink)",
            maxWidth: "none",
            h1: {
              fontFamily: "var(--font-serif), Georgia, serif",
              fontSize: "30px",
              fontWeight: "400",
              letterSpacing: "-0.015em",
              color: "var(--ink)",
              marginTop: "0",
              marginBottom: "1.25rem",
            },
            h2: {
              fontFamily: "var(--font-serif), Georgia, serif",
              fontSize: "22px",
              fontWeight: "400",
              color: "var(--ink)",
              marginTop: "2.25rem",
              marginBottom: "0.75rem",
            },
            h3: {
              fontFamily: "var(--font-serif), Georgia, serif",
              fontSize: "18px",
              fontWeight: "400",
              color: "var(--ink)",
              marginTop: "1.75rem",
              marginBottom: "0.5rem",
            },
            p: { marginTop: "0", marginBottom: "1.1rem", color: "var(--ink)" },
            a: {
              color: "var(--accent)",
              textDecoration: "underline",
              textUnderlineOffset: "3px",
              textDecorationThickness: "1px",
              textDecorationColor: "var(--line)",
              fontWeight: "400",
              "&:hover": { textDecorationColor: "var(--accent)" },
            },
            strong: { fontWeight: "500", color: "var(--ink)" },
            blockquote: {
              fontFamily: "var(--font-serif), Georgia, serif",
              fontStyle: "normal",
              fontSize: "18px",
              color: "var(--muted)",
              borderLeftColor: "var(--accent)",
              paddingLeft: "1.25rem",
            },
            li: { marginTop: "0.2rem", marginBottom: "0.2rem" },
            "ul > li::marker": { color: "var(--faint)" },
            "ol > li::marker": { color: "var(--faint)" },
            hr: {
              borderColor: "var(--line)",
              marginTop: "2.5rem",
              marginBottom: "2.5rem",
            },
            img: { borderRadius: "var(--radius-lg)" },
            figcaption: {
              fontFamily: "var(--font-mono), ui-monospace, monospace",
              fontSize: "11px",
              letterSpacing: "0.11em",
              textTransform: "uppercase",
              color: "var(--faint)",
            },
            pre: {
              backgroundColor: "var(--surface)",
              color: "var(--ink)",
              borderRadius: "var(--radius-lg)",
              padding: "1rem",
              overflowX: "auto",
              fontSize: "13px",
              lineHeight: "1.7",
              border: "1px solid var(--line)",
            },
            code: {
              backgroundColor: "var(--surface)",
              color: "var(--ink)",
              border: "1px solid var(--line)",
              borderRadius: "4px",
              padding: "0.1rem 0.35rem",
              fontWeight: "400",
              fontSize: "13px",
              "&::before": { content: "none" },
              "&::after": { content: "none" },
            },
            "pre code": {
              backgroundColor: "transparent",
              border: "none",
              borderRadius: "0",
              padding: "0",
              color: "inherit",
              fontSize: "inherit",
            },
            table: { fontSize: "14px" },
            "thead th": {
              color: "var(--ink)",
              borderBottomColor: "var(--line)",
              fontWeight: "500",
            },
            "tbody td": { borderBottomColor: "var(--line)" },
          },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
