#!/usr/bin/env node
/**
 * Generates public/sw.js (and out/sw.js) after the static export.
 *
 * The precache list has to be derived from the real build output because
 * Next's chunk filenames are content-hashed and unknowable ahead of time.
 * Runs as `postbuild`.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { buildPrecacheList } from "./lib/precache.mjs";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "out");

/** Every file in `out/`, as absolute-style public paths. */
async function walk(dir, base = "") {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const rel = `${base}/${entry.name}`;
    if (entry.isDirectory()) {
      files.push(...(await walk(path.join(dir, entry.name), rel)));
    } else {
      files.push(rel);
    }
  }
  return files;
}

const worker = (version, precache) => `/**
 * Generated by scripts/build-sw.mjs — do not edit by hand.
 * Rebuilt on every \`npm run build\`.
 */
const VERSION = ${JSON.stringify(version)};
const CACHE = \`atarax-\${VERSION}\`;
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const OFFLINE_URL = "/offline/";

/**
 * trailingSlash: true means routes are exported as /about/ — a request for
 * /about must resolve to the same cache entry or every un-slashed link misses.
 */
function normalizeRoute(url) {
  const { pathname } = new URL(url);
  if (pathname === "" || pathname === "/") return "/";
  const last = pathname.split("/").pop();
  if (last && last.includes(".")) return pathname;
  return pathname.endsWith("/") ? pathname : pathname + "/";
}

function isImmutable(pathname) {
  return pathname.startsWith("/_next/static/") || pathname.startsWith("/_img/");
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // addAll is atomic: one 404 would reject the whole install and leave the
      // site with no worker, so each entry is added independently.
      .then((cache) =>
        Promise.all(
          PRECACHE.map((url) =>
            cache.add(new Request(url, { cache: "reload" })).catch(() => {})
          )
        )
      )
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Documents: network-first so a deploy is picked up immediately, falling
  // back to cache, then to the offline page.
  if (request.mode === "navigate" || request.destination === "document") {
    const key = normalizeRoute(request.url);
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(key, copy));
          return response;
        })
        .catch(() =>
          caches
            .match(key)
            .then((hit) => hit || caches.match(OFFLINE_URL))
            .then((hit) => hit || Response.error())
        )
    );
    return;
  }

  // Hashed assets: cache-first, safe forever because the URL changes when the
  // content does.
  if (isImmutable(url.pathname)) {
    event.respondWith(
      caches.match(request).then(
        (hit) =>
          hit ||
          fetch(request).then((response) => {
            if (response.ok) {
              const copy = response.clone();
              caches.open(CACHE).then((cache) => cache.put(request, copy));
            }
            return response;
          })
      )
    );
    return;
  }

  // Data: stale-while-revalidate — instant paint, fresh on the next visit.
  if (url.pathname.endsWith(".json")) {
    event.respondWith(
      caches.match(request).then((hit) => {
        const network = fetch(request)
          .then((response) => {
            if (response.ok) {
              const copy = response.clone();
              caches.open(CACHE).then((cache) => cache.put(request, copy));
            }
            return response;
          })
          .catch(() => hit);
        return hit || network;
      })
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request))
  );
});
`;

async function main() {
  let files;
  try {
    files = await walk(OUT);
  } catch {
    console.error("build-sw: out/ not found — run `next build` first");
    process.exit(1);
  }

  const precache = buildPrecacheList(files);

  // Version from the precache list: any changed chunk hash changes the cache
  // name, which is what evicts the previous generation on activate.
  const version = createHash("sha256")
    .update(precache.join("\n"))
    .digest("hex")
    .slice(0, 12);

  const source = worker(version, precache);

  // Written to both: public/ so `next dev` serves it, and out/ because the
  // export has already happened by the time this runs.
  await fs.writeFile(path.join(ROOT, "public", "sw.js"), source);
  await fs.writeFile(path.join(OUT, "sw.js"), source);

  console.log(
    `build-sw: version ${version}, ${precache.length} precached entries`
  );
}

main().catch((err) => {
  console.error("build-sw failed:", err);
  process.exit(1);
});
